'use strict';
/**
 * ZK Expense Splitter — Witness Interface Module
 *
 * Generated by the Compact compiler to define the witness function interface.
 * The actual implementations are provided by the DApp (src/witnesses.ts)
 * and injected at runtime through the Midnight.js provider system.
 *
 * In the real compiled output, this module exports the witness function
 * signatures that the DApp developer must implement in TypeScript.
 */

/**
 * Witness function identifiers as declared in the Compact contract.
 * The Midnight SDK uses these names to dispatch to the correct TypeScript implementation.
 */
const WITNESS_FUNCTIONS = {
  GET_EXPENSE_AMOUNT: 'get_expense_amount',
  GET_MEMBER_SECRET: 'get_member_secret',
  GET_GROUP_EXPENSES: 'get_group_expenses',
};

module.exports = {
  WITNESS_FUNCTIONS,
};
