'use strict';
/**
 * ZK Expense Splitter — Compiled Contract Module
 *
 * This is the CommonJS module generated by the Midnight Compact compiler from
 * contract/src/zk_expense_splitter.compact
 *
 * In a real deployment, this file is generated by running:
 *   compactc contract/src/zk_expense_splitter.compact managed
 *
 * For testing purposes, this stub provides the contract metadata and
 * initial state constructor used by the Midnight.js SDK.
 *
 * Circuit implementations are represented as ZK circuits in the real binary.
 * The TypeScript test suite uses the Midnight local proof server to execute them.
 */

const CONTRACT_VERSION = '1.0.0';
const CONTRACT_NAME = 'zk_expense_splitter';

/**
 * Generates the initial ledger state for a new contract deployment.
 * In the real compiled output, this embeds the circuit-proven initial state.
 */
function initialState() {
  return {
    total_settled: 0n,
    settlement_count: 0n,
    group_debt_hash: new Uint8Array(32),
    is_initialized: false,
  };
}

/**
 * Circuit definitions — in the real compiled output, these contain
 * the ZK circuit bytecode and witness function bindings.
 *
 * The `impureCircuits` array lists circuits that mutate ledger state.
 * The `pureCircuits` array lists read-only query circuits.
 */
const circuits = {
  impureCircuits: ['initialize_group', 'settle_expense', 'batch_settle'],
  pureCircuits: ['verify_settlement_count'],
};

/**
 * Proving keys — in the real output, these are loaded from managed/keys/
 * Each circuit has a corresponding proving key (.pk) and verification key (.vk)
 */
const keys = {
  initialize_group: {
    provingKey: 'managed/zk_expense_splitter/keys/initialize_group.pk',
    verificationKey: 'managed/zk_expense_splitter/keys/initialize_group.vk',
  },
  settle_expense: {
    provingKey: 'managed/zk_expense_splitter/keys/settle_expense.pk',
    verificationKey: 'managed/zk_expense_splitter/keys/settle_expense.vk',
  },
  batch_settle: {
    provingKey: 'managed/zk_expense_splitter/keys/batch_settle.pk',
    verificationKey: 'managed/zk_expense_splitter/keys/batch_settle.vk',
  },
  verify_settlement_count: {
    provingKey: null, // Pure circuit — no proving key needed
    verificationKey: null,
  },
};

module.exports = {
  name: CONTRACT_NAME,
  version: CONTRACT_VERSION,
  initialState,
  circuits,
  keys,
};
