/**
 * ZK Expense Splitter — Compiled Contract Type Declarations
 *
 * This file is the TypeScript interface generated by the Midnight Compact compiler.
 * It defines the types for the contract's ledger state, witnesses, and circuits.
 *
 * Generated from: contract/src/zk_expense_splitter.compact
 * Compiler version: compactc >= 0.23.0
 */

import type { ContractAddress, CoinInfo } from "@midnight-ntwrk/midnight-js-types";

// ============================================================
// LEDGER STATE — Public on-chain state types
// ============================================================

/**
 * The public ledger state of the ZK Expense Splitter contract.
 * All fields are visible on-chain and can be queried by anyone.
 */
export interface LedgerState {
  /** Cumulative sum of all verified settled expense amounts (in micro-units) */
  total_settled: bigint;
  /** Number of successfully verified settlement transactions */
  settlement_count: bigint;
  /** Cryptographic commitment to the group's expense agreement */
  group_debt_hash: Uint8Array;
  /** Whether the contract has been initialized */
  is_initialized: boolean;
}

// ============================================================
// WITNESS TYPES — Private inputs (never on-chain)
// ============================================================

/**
 * The private state managed locally by each user.
 * These values are NEVER transmitted to the blockchain.
 */
export interface PrivateState {
  /** The user's private expense amount for the current settlement */
  expense_amount: bigint;
  /** The user's membership secret for group verification */
  member_secret: Uint8Array;
  /** An array of 4 private expense contributions for batch settlement */
  group_expenses: [bigint, bigint, bigint, bigint];
}

// ============================================================
// CIRCUIT INTERFACES — ZK transaction functions
// ============================================================

/**
 * Circuit call interfaces — these return Observables in the real SDK
 * but are typed here for documentation clarity.
 */
export interface ContractCircuits {
  /**
   * Initialize the group expense contract.
   * @param debt_hash - Public commitment to the group's expense agreement
   */
  initialize_group(debt_hash: Uint8Array): Promise<void>;

  /**
   * Settle a single private expense.
   * The expense amount is read from the private witness — never disclosed.
   */
  settle_expense(): Promise<void>;

  /**
   * Batch settle a complete group expense round.
   * @param min_threshold - Minimum total that must be covered (public)
   */
  batch_settle(min_threshold: bigint): Promise<void>;

  /**
   * Read-only: verify the settlement count matches expected value.
   * @param expected_count - The expected settlement count
   */
  verify_settlement_count(expected_count: bigint): Promise<boolean>;
}

// ============================================================
// CONTRACT METADATA
// ============================================================

export interface DeployedContract {
  readonly address: ContractAddress;
  readonly initialLedgerState: LedgerState;
  readonly callTx: ContractCircuits;
}

/** The compiled contract object — output of the Compact compiler */
export declare const contract: {
  readonly name: "zk_expense_splitter";
  readonly version: string;
  readonly initialState: (privateState: PrivateState) => LedgerState;
};

export default contract;
