#!/usr/bin/env node
/**
 * scripts/patch-cjs.js
 *
 * Patches @midnight-ntwrk packages that ship ESM-only bundles but declare CJS
 * export paths in their package.json (dist/cjs/). This causes MODULE_NOT_FOUND
 * errors in Node.js / ts-node (CJS) environments.
 *
 * Affected packages in @midnight-ntwrk v4.1.1:
 *   - compact-js       (dist/cjs/ entirely missing)
 *   - platform-js      (dist/cjs/ entirely missing)
 *   - wallet-sdk-address-format  (only ESM export, no "require" entry)
 *
 * This script creates lightweight CJS proxy shims that delegate to the real
 * ESM files via dynamic import(). Run automatically via postinstall.
 *
 * Usage:
 *   node scripts/patch-cjs.js
 *   # or automatically after npm install via postinstall hook
 */

const fs = require('fs');
const path = require('path');

const NM = path.resolve(__dirname, '../node_modules/@midnight-ntwrk');

// ============================================================
// CJS SHIM TEMPLATE
// ============================================================
function makeShim(esmRelPath) {
  return `'use strict';
// CJS shim — delegates to ESM via dynamic import()
// Auto-generated by scripts/patch-cjs.js to fix missing dist/cjs/ bundles.
const path = require('path');
const esmFile = path.resolve(__dirname, ${JSON.stringify(esmRelPath)});
let _mod = null;
let _p = null;
function _load() { if (!_p) _p = import(esmFile).then(m => { _mod = m; }); return _p; }
_load().catch(() => {});
module.exports = new Proxy({}, {
  get(_, p) {
    if (p === '__esModule') return true;
    if (_mod) return _mod[p];
    return undefined;
  }
});
`;
}

// ============================================================
// PACKAGES TO PATCH
// ============================================================
const PATCHES = [
  {
    pkg: 'compact-js',
    files: [
      'effect/index.js',
      'effect/CompactContext.js',
      'effect/CompiledContract.js',
      'effect/Contract.js',
      'effect/ContractConfigurationError.js',
      'effect/ContractExecutable.js',
      'effect/ContractExecutableRuntime.js',
      'effect/ContractRuntimeError.js',
      'effect/ZKConfiguration.js',
      'effect/ZKConfigurationReadError.js',
      'effect/internal/compactContext.js',
      'index.js',
    ],
  },
  {
    pkg: 'platform-js',
    files: [
      'effect/index.js',
      'effect/CoinPublicKey.js',
      'effect/Configuration.js',
      'effect/ContractAddress.js',
      'effect/DomainSeparator.js',
      'effect/Hex.js',
      'effect/IntegerRange.js',
      'effect/NetworkId.js',
      'effect/NetworkIdMoniker.js',
      'effect/ParseError.js',
      'effect/SigningKey.js',
      'effect/internal/hex.js',
      'index.js',
    ],
  },
];

// ============================================================
// WALLET-SDK-ADDRESS-FORMAT — needs "require" export + CJS shim
// ============================================================
function patchWalletSdkAddressFormat() {
  const pkgDir = path.join(NM, 'wallet-sdk-address-format');
  if (!fs.existsSync(pkgDir)) return;

  const pkgJsonPath = path.join(pkgDir, 'package.json');
  const cjsPath = path.join(pkgDir, 'dist', 'index.cjs');
  const esmRel = './index.js';

  // Write CJS shim
  if (!fs.existsSync(cjsPath)) {
    // Compute relative path from cjs dir to esm file
    const cjsDir = path.dirname(cjsPath);
    const esmAbs = path.join(pkgDir, 'dist', 'index.js');
    const rel = './' + path.relative(cjsDir, esmAbs).replace(/\\/g, '/');
    fs.writeFileSync(cjsPath, makeShim(rel));
    console.log(`  ✅ wallet-sdk-address-format/dist/index.cjs`);
  }

  // Update package.json exports
  const pkg = JSON.parse(fs.readFileSync(pkgJsonPath, 'utf8'));
  const dotExport = pkg.exports?.['.'];
  if (dotExport && !dotExport.require) {
    dotExport.require = './dist/index.cjs';
    pkg.main = './dist/index.cjs';
    fs.writeFileSync(pkgJsonPath, JSON.stringify(pkg, null, 2));
    console.log(`  ✅ wallet-sdk-address-format/package.json (added "require" export)`);
  }
}

// ============================================================
// MAIN PATCH LOOP
// ============================================================
let patched = 0;
let skipped = 0;

for (const { pkg, files } of PATCHES) {
  const pkgDir = path.join(NM, pkg);
  if (!fs.existsSync(pkgDir)) {
    console.log(`  ⚠️  Package not found: @midnight-ntwrk/${pkg}`);
    continue;
  }

  for (const file of files) {
    const esmPath = path.join(pkgDir, 'dist', 'esm', file);
    const cjsPath = path.join(pkgDir, 'dist', 'cjs', file);

    if (!fs.existsSync(esmPath)) {
      // Skip — ESM source doesn't exist either
      continue;
    }

    if (fs.existsSync(cjsPath)) {
      skipped++;
      continue; // Already patched
    }

    // Create directory
    fs.mkdirSync(path.dirname(cjsPath), { recursive: true });

    // Compute relative path from CJS file to ESM file
    const cjsDir = path.dirname(cjsPath);
    let rel = path.relative(cjsDir, esmPath).replace(/\\/g, '/');
    if (!rel.startsWith('.')) rel = './' + rel;

    fs.writeFileSync(cjsPath, makeShim(rel));
    console.log(`  ✅ ${pkg}/dist/cjs/${file}`);
    patched++;
  }
}

patchWalletSdkAddressFormat();

if (patched === 0 && skipped > 0) {
  console.log(`  ℹ️  All CJS shims already present (${skipped} files skipped)`);
} else {
  console.log(`\n  Created ${patched} CJS shim(s) for @midnight-ntwrk packages.`);
}
