/**
 * ZK Expense Splitter — Real Deployment Script
 *
 * Deploys the compiled ZK Expense Splitter contract to the Midnight Preview network
 * using the official @midnight-ntwrk SDK. On success, writes a deployment-receipt.json
 * file containing the real on-chain contract address.
 *
 * Usage:
 *   npm run deploy
 *   # or with env override:
 *   MIDNIGHT_NETWORK=preprod npm run deploy
 *
 * Prerequisites:
 *   1. Contract compiled:  npm run compile  (requires compactc in PATH)
 *   2. Proof server running:
 *      docker run -d --name midnight-proof-server -p 6300:6300 midnightntwrk/proof-server:latest
 *   3. Environment variables configured (copy .env.example → .env):
 *      MIDNIGHT_WALLET_SEED   — 24-word BIP-39 mnemonic with tDUST balance
 *      MIDNIGHT_NETWORK       — preview | preprod (default: preview)
 *
 * Output:
 *   Console: real contract address + tx hash
 *   File:    deployment-receipt.json (committed to repo as deployment evidence)
 */

import * as fs from 'fs';
import * as path from 'path';
import { NETWORK_CONFIG, stringToBytes32, bytesToHex, NetworkName } from './utils';
import { createInitialPrivateState, deriveGroupDebtHash } from './witnesses';

// ============================================================
// DEPLOYMENT CONFIGURATION
// ============================================================

const DEPLOYMENT_CONFIG = {
  /** Target network — override with MIDNIGHT_NETWORK env var */
  network: (process.env['MIDNIGHT_NETWORK'] ?? 'preview') as NetworkName,

  /** Group identifier for this expense splitter deployment */
  groupId: process.env['GROUP_ID'] ?? 'zk-expense-splitter-preview',

  /** Proof server URI */
  proofServerUri: process.env['MIDNIGHT_PROOF_SERVER_URI'] ?? 'http://localhost:6300',

  /** Indexer URI */
  indexerUri:
    process.env['MIDNIGHT_INDEXER_URI'] ??
    'https://indexer.preview.midnight.network/api/v1/graphql',

  /** Private state storage path (leveldb) */
  privateStateDir: process.env['MIDNIGHT_PRIVATE_STATE_DIR'] ?? './.private-state',

  /** 24-word BIP-39 mnemonic for signing — NEVER commit to git */
  walletSeed: process.env['MIDNIGHT_WALLET_SEED'] ?? '',
};

// ============================================================
// REAL MIDNIGHT SDK DEPLOYMENT
// ============================================================

/**
 * Deploys the contract using the real Midnight.js SDK.
 *
 * This function requires:
 *  - Real compiled .pk/.vk artifacts in managed/zk_expense_splitter/keys/
 *  - A running proof server (Docker)
 *  - A funded Lace/mnemonic wallet (MIDNIGHT_WALLET_SEED in .env)
 *
 * The deployContract() call submits a real transaction to the Preview network
 * and returns the canonical contract address assigned by the network.
 */
async function deployWithSdk(): Promise<{
  contractAddress: string;
  txHash: string;
  groupDebtHash: string;
}> {
  // Dynamic imports — these are the real @midnight-ntwrk packages.
  // They require the compiled .pk circuit artifacts to exist at the paths below.
  const { setNetworkId } = await import('@midnight-ntwrk/midnight-js-network-id');
  const { deployContract } = await import('@midnight-ntwrk/midnight-js-contracts');
  const { httpClientProofProvider } = await import(
    '@midnight-ntwrk/midnight-js-http-client-proof-provider'
  );
  const { indexerPublicDataProvider } = await import(
    '@midnight-ntwrk/midnight-js-indexer-public-data-provider'
  );
  const { levelPrivateStateProvider } = await import(
    '@midnight-ntwrk/midnight-js-level-private-state-provider'
  );

  const networkConfig = NETWORK_CONFIG[DEPLOYMENT_CONFIG.network];
  if (!networkConfig) {
    throw new Error(`Unknown network: "${DEPLOYMENT_CONFIG.network}"`);
  }

  // Set network identity (TestNet for preview/preprod, MainNet for mainnet)
  setNetworkId(networkConfig.networkId);

  // Derive group commitment hash
  const debtHash = deriveGroupDebtHash(DEPLOYMENT_CONFIG.groupId);
  const debtHashHex = `0x${bytesToHex(debtHash)}`;

  console.log(`  Network ID:       ${networkConfig.networkId}`);
  console.log(`  Indexer URI:      ${DEPLOYMENT_CONFIG.indexerUri}`);
  console.log(`  Proof Server URI: ${DEPLOYMENT_CONFIG.proofServerUri}`);
  console.log(`  Group ID:         ${DEPLOYMENT_CONFIG.groupId}`);
  console.log(`  Group Debt Hash:  ${debtHashHex}`);
  console.log('');

  // Load compiled contract module (generated by: npm run compile)
  // This is the real Compact-compiled TypeScript binding.
  const compiledContract = require('../managed/zk_expense_splitter/contract/index.cjs');

  // Configure provider stack
  const providers = {
    privateStateProvider: levelPrivateStateProvider({
      dbPath: DEPLOYMENT_CONFIG.privateStateDir,
    }),
    publicDataProvider: indexerPublicDataProvider(DEPLOYMENT_CONFIG.indexerUri),
    proofProvider: httpClientProofProvider(
      DEPLOYMENT_CONFIG.proofServerUri,
      // zkConfigProvider loads the real .pk binary keys from managed/zk_expense_splitter/keys/
      // These files start with "midnight:prover-key[v7]" — real circuit artifacts.
      compiledContract.zkConfigProvider(
        path.resolve(__dirname, '../managed/zk_expense_splitter'),
        compiledContract
      )
    ),
    // For mnemonic-based signing (non-browser deployment)
    walletProvider: await buildWalletProvider(networkConfig),
    midnightProvider: await buildMidnightProvider(networkConfig),
  };

  // Deploy the contract — this submits a real transaction to the Midnight Preview network
  console.log('  ⏳ Submitting deployment transaction to Midnight Preview...');
  const deployed = await deployContract(providers, {
    compiledContract,
    initialPrivateState: createInitialPrivateState(),
  });

  // Call initialize_group circuit to set the group hash on-chain
  console.log('  ⏳ Calling initialize_group() circuit...');
  await deployed.callTx.initialize_group(debtHash);

  const contractAddress: string = deployed.deployTxData.public.contractAddress;
  const txHash: string = deployed.deployTxData.public.txId ?? '';

  return { contractAddress, txHash, groupDebtHash: debtHashHex };
}

/**
 * Build a wallet provider from a BIP-39 mnemonic seed.
 * Used for non-browser (CI / script) deployments.
 */
async function buildWalletProvider(networkConfig: { networkId: string }) {
  if (!DEPLOYMENT_CONFIG.walletSeed) {
    throw new Error(
      'MIDNIGHT_WALLET_SEED environment variable is required for deployment.\n' +
      'Set it in your .env file. The seed must be a 24-word BIP-39 mnemonic\n' +
      'with a tDUST balance on the target network.\n' +
      'Get tDUST at: https://faucet.preview.midnight.network/'
    );
  }

  // The Midnight SDK supports mnemonic-based wallets for script deployments.
  // In production browser apps, this is handled by the Lace DApp connector.
  try {
    const { mnemonicWalletProvider } = await import('@midnight-ntwrk/midnight-js-types');
    return mnemonicWalletProvider({
      mnemonic: DEPLOYMENT_CONFIG.walletSeed,
      networkId: networkConfig.networkId as 'TestNet' | 'MainNet',
    });
  } catch {
    // Fallback: some SDK versions expose this under a different path
    throw new Error(
      'Could not import mnemonicWalletProvider from @midnight-ntwrk/midnight-js-types.\n' +
      'Ensure @midnight-ntwrk packages are installed at compatible versions (see package.json).\n' +
      'For browser deployments, use the Lace DApp connector instead.'
    );
  }
}

async function buildMidnightProvider(networkConfig: { networkId: string; nodeUri?: string }) {
  const nodeUri = networkConfig.nodeUri ?? 'https://rpc.preview.midnight.network';
  try {
    const { nodeMidnightProvider } = await import('@midnight-ntwrk/midnight-js-types');
    return nodeMidnightProvider({ nodeUri });
  } catch {
    throw new Error(
      `Could not build Midnight provider for node URI: ${nodeUri}.\n` +
      'Ensure the RPC endpoint is reachable.'
    );
  }
}

// ============================================================
// DEPLOYMENT RUNNER
// ============================================================

async function deploy(): Promise<void> {
  console.log('');
  console.log('╔════════════════════════════════════════════════════════════╗');
  console.log('║         ZK Expense Splitter — Real Deployment Script       ║');
  console.log('║            Midnight Network Builder Program                ║');
  console.log('╚════════════════════════════════════════════════════════════╝');
  console.log('');

  // Step 1: Validate network config
  console.log('📋 Deployment Configuration');
  console.log('─'.repeat(60));
  const networkConfig = NETWORK_CONFIG[DEPLOYMENT_CONFIG.network];
  if (!networkConfig) {
    throw new Error(`Unknown network: "${DEPLOYMENT_CONFIG.network}"`);
  }

  // Step 2: Verify compiled artifacts exist
  console.log('🔍 Verifying Compiled Circuit Artifacts');
  console.log('─'.repeat(60));
  const expectedKeys = [
    'managed/zk_expense_splitter/keys/settle_expense.pk',
    'managed/zk_expense_splitter/keys/settle_expense.vk',
    'managed/zk_expense_splitter/keys/batch_settle.pk',
    'managed/zk_expense_splitter/keys/batch_settle.vk',
    'managed/zk_expense_splitter/keys/initialize_group.pk',
    'managed/zk_expense_splitter/keys/initialize_group.vk',
    'managed/zk_expense_splitter/contract/index.cjs',
  ];

  let allPresent = true;
  for (const keyPath of expectedKeys) {
    const absPath = path.resolve(__dirname, '..', keyPath);
    const exists = fs.existsSync(absPath);
    const size = exists ? fs.statSync(absPath).size : 0;
    // Real .pk files are 40KB+ — placeholder text files are <1KB
    const isReal = exists && (keyPath.endsWith('.cjs') ? size > 100 : size > 10_000);
    console.log(`  ${isReal ? '✅' : '❌'} ${keyPath} (${(size / 1024).toFixed(1)} KB)`);
    if (!isReal) allPresent = false;
  }

  if (!allPresent) {
    throw new Error(
      '\nSome circuit artifacts are missing or are placeholder files.\n' +
      'Run: npm run compile\n' +
      'Requires: compactc from https://docs.midnight.network/develop/tutorial/building/'
    );
  }
  console.log('');

  // Step 3: Check proof server
  console.log('🌐 Connecting to Infrastructure');
  console.log('─'.repeat(60));
  const proofServerAvailable = await checkProofServer(DEPLOYMENT_CONFIG.proofServerUri);
  if (proofServerAvailable) {
    console.log(`  ✅ Proof Server: ONLINE at ${DEPLOYMENT_CONFIG.proofServerUri}`);
  } else {
    throw new Error(
      `Proof server not running at ${DEPLOYMENT_CONFIG.proofServerUri}.\n` +
      'Start it with:\n' +
      '  docker run -d --name midnight-proof-server -p 6300:6300 midnightntwrk/proof-server:latest'
    );
  }
  console.log('');

  // Step 4: Deploy
  console.log('🚀 Deploying to Midnight Preview Network');
  console.log('─'.repeat(60));
  const { contractAddress, txHash, groupDebtHash } = await deployWithSdk();

  console.log('');
  console.log('┌─────────────────────────────────────────────────────────────┐');
  console.log('│                  ✅ DEPLOYMENT SUCCESSFUL                    │');
  console.log('├─────────────────────────────────────────────────────────────┤');
  console.log(`│  Contract Address: ${contractAddress}`);
  console.log(`│  Transaction Hash: ${txHash}`);
  console.log(`│  Network:          Midnight Preview Network`);
  console.log('└─────────────────────────────────────────────────────────────┘');
  console.log('');

  // Step 5: Write deployment-receipt.json
  const receipt = {
    contractAddress,
    txHash,
    network: DEPLOYMENT_CONFIG.network,
    networkLabel: 'Midnight Preview Network',
    networkId: 'TestNet',
    deployedAt: new Date().toISOString(),
    groupId: DEPLOYMENT_CONFIG.groupId,
    groupDebtHash,
    circuits: ['initialize_group', 'settle_expense', 'batch_settle', 'verify_settlement_count'],
    compilerVersion: '0.31.1',
    languageVersion: '0.23.0',
    runtimeVersion: '0.16.0',
    indexerUri: DEPLOYMENT_CONFIG.indexerUri,
    explorerQuery: `https://indexer.preview.midnight.network/api/v1/graphql\n` +
      `# Query:\n` +
      `# { contract(address: "${contractAddress}") { state { total_settled settlement_count group_debt_hash is_initialized } } }`,
  };

  const receiptPath = path.resolve(__dirname, '../deployment-receipt.json');
  fs.writeFileSync(receiptPath, JSON.stringify(receipt, null, 2));

  console.log('📄 Deployment Receipt');
  console.log('═'.repeat(60));
  console.log(`  Written to: deployment-receipt.json`);
  console.log(`  CONTRACT:   ${contractAddress}`);
  console.log(`  NETWORK:    Midnight Preview Network`);
  console.log(`  DEBT HASH:  ${groupDebtHash}`);
  console.log('');
  console.log('  Next Steps:');
  console.log('  1. Commit deployment-receipt.json to your repository');
  console.log('  2. Update README.md Contract Address with the real address above');
  console.log(`  3. Verify on indexer: ${DEPLOYMENT_CONFIG.indexerUri}`);
  console.log('');
  console.log('═'.repeat(60));
  console.log('  🌙 Powered by Midnight Network — Privacy by default.');
  console.log('═'.repeat(60));
  console.log('');
}

// ============================================================
// HELPER FUNCTIONS
// ============================================================

async function checkProofServer(uri: string): Promise<boolean> {
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 3000);
    const response = await fetch(`${uri}/api/v1/status`, { signal: controller.signal });
    clearTimeout(timeout);
    return response.status < 500;
  } catch {
    return false;
  }
}

// ============================================================
// ENTRY POINT
// ============================================================

deploy()
  .then(() => process.exit(0))
  .catch((error: unknown) => {
    console.error('');
    console.error('❌ Deployment Failed:');
    if (error instanceof Error) {
      console.error(`   ${error.message}`);
      if (process.env['DEBUG']) console.error(error.stack);
    } else {
      console.error(error);
    }
    console.error('');
    console.error('Troubleshooting:');
    console.error('  1. Is the proof server running?');
    console.error('     docker run -d -p 6300:6300 midnightntwrk/proof-server:latest');
    console.error('  2. Is the contract compiled?');
    console.error('     npm run compile  (requires compactc)');
    console.error('  3. Is MIDNIGHT_WALLET_SEED set in your .env with a funded account?');
    console.error('     Get tDUST at: https://faucet.preview.midnight.network/');
    process.exit(1);
  });
